In [1]:
import pandas as pd
import os

In [2]:
#os.listdir()

In [3]:
prop_df = pd.read_csv('RTB_Register_Data.csv')
print("num records:"+str(len(prop_df)))
prop_df.head()

num records:1966

,AddressLine1,AddressLine2,AddressLine3,AddressLine4,AddressLine5,Eircode,County,NoOfBedrooms
0,1 Ashleigh Court,Maynooth Road,Celbridge,NaN,NaN,W23KW50,Kildare,1.0
1,1 Beaufield Gardens,Maynooth,NaN,NaN,NaN,W23X7F1,Kildare,5.0
2,1 Beaufield Lawns,Maynooth,NaN,NaN,NaN,W23W5H2,Kildare,3.0
3,"1, 1 Beaufield Lawns",Maynooth,NaN,NaN,NaN,W23W5H2,Kildare,3.0
4,1 Brookfield Avenue,Maynooth,NaN,NaN,NaN,W23F8D2,Kildare,3.0

In [4]:
address_cols = ['AddressLine'+str(l) for l in range(1,6)]
str_cols = address_cols+['Eircode', 'County']
int_cols = ['NoOfBedrooms']

In [5]:
prop_df[str_cols] = prop_df[str_cols].fillna('')
prop_df[int_cols] = prop_df[int_cols].fillna(0)

In [6]:
prop_df = prop_df[prop_df['NoOfBedrooms'] == 2]
print("num records:"+str(len(prop_df)))

prop_df.head()

num records:749

,AddressLine1,AddressLine2,AddressLine3,AddressLine4,AddressLine5,Eircode,County,NoOfBedrooms
8,1 Crodaun Court,Maynooth Road,Celbridge,,,W23FR33,Kildare,2.0
9,1 Deerpark House,Lyreen Manor,Maynooth,,,W23H950,Kildare,2.0
12,1 Earls Court,Lyreen Manor,Maynooth,,,W23XW29,Kildare,2.0
13,1 Elm Court,Maynooth Road,Celbridge,,,W23H2T4,Kildare,2.0
15,1 Hayfield Square,Maynooth,,,,W23Y8P5,Kildare,2.0

In [7]:
for ac in address_cols:
    prop_df = prop_df.loc[~prop_df[ac].str.contains("maynooth road", case=False)]
print("num records:"+str(len(prop_df)))
prop_df.head()

num records:713

,AddressLine1,AddressLine2,AddressLine3,AddressLine4,AddressLine5,Eircode,County,NoOfBedrooms
9,1 Deerpark House,Lyreen Manor,Maynooth,,,W23H950,Kildare,2.0
12,1 Earls Court,Lyreen Manor,Maynooth,,,W23XW29,Kildare,2.0
15,1 Hayfield Square,Maynooth,,,,W23Y8P5,Kildare,2.0
20,1 Manor Court,Maynooth,,,,W23TX24,Kildare,2.0
22,1 Mariavilla Grange,Mariavilla,Maynooth,,,W23Y2DN,Kildare,2.0

In [13]:
prop_df['AddressFull'] = prop_df[address_cols].apply(", ".join, axis=1)
for _ in range(3):
    prop_df['AddressFull'] = prop_df['AddressFull'].str.replace(', ,', ',')
for _ in range(2):
    prop_df['AddressFull'] = prop_df['AddressFull'].str.rstrip(' ')
    prop_df['AddressFull'] = prop_df['AddressFull'].str.rstrip(',')
prop_df[['AddressFull', 'Eircode']].head()

                                  AddressFull  Eircode
9    1 Deerpark House, Lyreen Manor, Maynooth  W23H950
12      1 Earls Court, Lyreen Manor, Maynooth  W23XW29
15                1 Hayfield Square, Maynooth  W23Y8P5
20                    1 Manor Court, Maynooth  W23TX24
22  1 Mariavilla Grange, Mariavilla, Maynooth  W23Y2DN

In [15]:
prop_df.loc[prop_df['AddressFull'].str.contains("lyreen", case=False)]

,AddressLine1,AddressLine2,AddressLine3,AddressLine4,AddressLine5,Eircode,County,NoOfBedrooms,AddressFull
9,1 Deerpark House,Lyreen Manor,Maynooth,,,W23H950,Kildare,2.0,"1 Deerpark House, Lyreen Manor, Maynooth"
12,1 Earls Court,Lyreen Manor,Maynooth,,,W23XW29,Kildare,2.0,"1 Earls Court, Lyreen Manor, Maynooth"
54,10 Castlekeep,Lyreen Manor,Maynooth,,,W23D5D4,Kildare,2.0,"10 Castlekeep, Lyreen Manor, Maynooth"
68,10 Ormond House,Lyreen Manor,Maynooth,,,W23X757,Kildare,2.0,"10 Ormond House, Lyreen Manor, Maynooth"
106,11 Earls Court,Lyreen,Maynooth,,,W23AX53,Kildare,2.0,"11 Earls Court, Lyreen, Maynooth"
...,...,...,...,...,...,...,...,...,...
1805,Apartment 8,Geraldine House,Lyreen Manor,Maynooth,,W23FY62,Kildare,2.0,"Apartment 8, Geraldine House, Lyreen Manor, Ma..."
1817,Apartment 9,Donadea House,Lyreen Manor,Maynooth,,W23H393,Kildare,2.0,"Apartment 9, Donadea House, Lyreen Manor, Mayn..."
1818,Apartment 9,Donadea House,Lyreen Manor,Maynooth,,W23H393,Kildare,2.0,"Apartment 9, Donadea House, Lyreen Manor, Mayn..."
1823,Apartment 9,Ormond House,Lyreen Manor,Maynooth,,W23EV57,Kildare,2.0,"Apartment 9, Ormond House, Lyreen Manor, Maynooth"
1824,Apartment 9,Ormond House,Lyreen Manor,Maynooth,,W23EV57,Kildare,2.0,"Apartment 9, Ormond House, Lyreen Manor, Maynooth"

In [17]:
with open('PPR-ALL.csv') as f:
    print(f)

<_io.TextIOWrapper name='PPR-ALL.csv' mode='r' encoding='cp1252'>

In [21]:
#help(pd.read_csv)

In [24]:
price_df = pd.read_csv('PPR-ALL.csv', encoding = 'cp1252')
print("num records:"+str(len(price_df)))
price_df.head()

num records:543675

C:\Users\Anthony\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (3,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
0,01/01/2010,"5 Braemor Drive, Churchtown, Co.Dublin",Dublin,NaN,"€343,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
1,03/01/2010,"134 Ashewood Walk, Summerhill Lane, Portlaoise",Laois,NaN,"€185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
2,04/01/2010,"1 Meadow Avenue, Dundrum, Dublin 14",Dublin,NaN,"€438,500.00",No,No,Second-Hand Dwelling house /Apartment,NaN
3,04/01/2010,"1 The Haven, Mornington",Meath,NaN,"€400,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
4,04/01/2010,"11 Melville Heights, Kilkenny",Kilkenny,NaN,"€160,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

In [25]:
price_df = price_df[price_df['County'] == 'Kildare']
print("num records:"+str(len(price_df)))
price_df.head()

num records:27965

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
45,05/01/2010,"122 KINGSBRY, MAYNOOTH",Kildare,NaN,"€220,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
48,05/01/2010,"14 beaufield grove, maynooth",Kildare,NaN,"€190,000.00",Yes,No,Second-Hand Dwelling house /Apartment,NaN
51,05/01/2010,"153 Beechpark, Leixlip",Kildare,NaN,"€265,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
105,06/01/2010,"Garravogue, Prosperous",Kildare,NaN,"€70,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
113,07/01/2010,"108 Ryevale lawns, Leixlip, Co. Kildare",Kildare,NaN,"€362,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

In [26]:
price_df = price_df.loc[price_df['Address'].str.contains("maynooth", case=False)]
print("num records:"+str(len(price_df)))
price_df.head()

num records:2701

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
45,05/01/2010,"122 KINGSBRY, MAYNOOTH",Kildare,NaN,"€220,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
48,05/01/2010,"14 beaufield grove, maynooth",Kildare,NaN,"€190,000.00",Yes,No,Second-Hand Dwelling house /Apartment,NaN
120,07/01/2010,"22 The Green Moyglare Hall, Moyglare Road, May...",Kildare,NaN,"€323,237.88",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
191,08/01/2010,"apt 25 block 2, The view newtown hall, maynooth",Kildare,NaN,"€201,950.00",No,Yes,New Dwelling house /Apartment,less than 38 sq metres
250,11/01/2010,"No. 65 The Green, Moyglare Hall Moyglare Road,...",Kildare,NaN,"€285,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...

In [29]:
price_df[~price_df['Eircode'].isna()]

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
369988,27/05/2019,"24 Carton Wood, Dublin Road, Maynooth",Kildare,W23Y152,"€382,378.00",No,Yes,New Dwelling house /Apartment,NaN
471260,01/04/2021,"87 GRIFFIN RATH HALL, CELBRIDGE RD, MAYNOOTH",Kildare,W23P2R6,"€325,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
473262,20/04/2021,"31 COLLEGE GREEN, MAYNOOTH, KILDARE",Kildare,W23R8X3,"€400,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
474052,26/04/2021,"50 CARTON SQ, MAYNOOTH, KILDARE",Kildare,W23NTV0,"€325,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
474950,30/04/2021,"18 LAURENCE AVE, MAYNOOTH, KILDARE",Kildare,W23P4F5,"€240,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
...,...,...,...,...,...,...,...,...,...
539324,10/06/2022,"46 SILKEN VALE, MAYNOOTH, KILDARE",Kildare,W23F2P7,"€380,000.00",Yes,No,Second-Hand Dwelling house /Apartment,NaN
540023,15/06/2022,"52 MOYGLARE ABBEY, MAYNOOTH, KILDARE",Kildare,W23H7P9,"€496,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
540240,16/06/2022,"42 GREENFIELD DR, MAYNOOTH, KILDARE",Kildare,W23X434,"€485,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
541299,23/06/2022,"35 CARTON WOOD, DUBLIN ROAD, MAYNOOTH",Kildare,W23YW30,"€512,500.00",No,No,Second-Hand Dwelling house /Apartment,NaN
543653,15/07/2022,"30 HAYFIELD, STRAFFAN ROAD, MAYNOOTH",Kildare,W23TR04,"€390,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

TODOs:
- [ ] Get Eircodes (if empty) from each address to match against tenant register
- [ ] Do we want the rented houses that are not in the register (were not sold since before 2010)?
- [ ] Look at descriptions
- [ ] electricity bills
- [ ] pay landlords for info, get subscriotions from users who want to rent
- [ ] find start of lease and find ones 11 months in
- [ ] find uniqque landlords, could be a lot less than 700

In [31]:
price_df['Description of Property'].unique()

array(['Second-Hand Dwelling house /Apartment',
       'New Dwelling house /Apartment'], dtype=object)

In [33]:
price_df['Date of Sale (dd/mm/yyyy)'] = pd.to_datetime(price_df['Date of Sale (dd/mm/yyyy)'])

In [37]:
220*0.07/2

7.700000000000001

In [40]:
price_df[price_df['Date of Sale (dd/mm/yyyy)'] >= '2022-01-01'].sort_values('Price (€)')

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
529335,2022-06-04,"353 GREENFIELD, MAYNOOTH, COUNTY KILDARE",Kildare,W23Y2T0,"€140,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
524418,2022-03-03,"MAYNOOTH ROAD, PROSPEROUS, CO KILDARE",Kildare,NaN,"€160,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
531193,2022-04-19,"APT 32 MANOR COURT, MAYNOOTH, COUNTY KILDARE",Kildare,W23RK76,"€19,250.00",Yes,No,Second-Hand Dwelling house /Apartment,NaN
525641,2022-11-03,"2 LEINSTER LODGE, MAYNOOTH, COUNTY KILDARE",Kildare,W23A0C8,"€220,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
525086,2022-08-03,"7 LEINSTER COTTAGES, MAYNOOTH, KILDARE",Kildare,W23K2P5,"€220,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
...,...,...,...,...,...,...,...,...,...
530754,2022-04-13,"BALTRACEY, MAYNOOTH, KILDARE",Kildare,W23C1K7,"€850,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
516870,2022-01-17,"50 PARSONS HALL, MAYNOOTH, KILDARE",Kildare,W23N1W5,"€860,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
531084,2022-04-14,"KILMACREDOCK UPPER, MAYNOOTH, KILDARE",Kildare,W23D8C9,"€860,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
518122,2022-01-25,"79 LEINSTER WOOD SOUTH, CARTON DEMESNE, MAYNOOTH",Kildare,W23R3H6,"€910,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
538675,2022-07-06,"MOYGLARE, MAYNOOTH, CO KILDARE",Kildare,NaN,"€950,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN